fix(CI): streamline Ts workflow with C# workflow

diff --git a/.github/workflows/build_release.yaml b/.github/workflows/build_release.yaml
--- a/.github/workflows/build_release.yaml
+++ b/.github/workflows/build_release.yaml
@@ -7,13 +7,13 @@ on:
     branches: [master]
 
 jobs:
-  build:
-    name: Build release
+  buildCSharp:
+    name: Build release CSharp
     runs-on: windows-latest
 
     steps:
       - name: "Checkout Master Branch"
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Update Assembly Version
         shell: bash
@@ -53,16 +53,69 @@ jobs:
     outputs:
       tag: ${{ env.ReleaseVersion }}
 
-  deps:
+  BuildTypeScript:
+    name: Build release TypeScript
+    runs-on: ubuntu-latest
+    env:
+      CI: ""
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Set up Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20"
+          registry-url: "https://registry.npmjs.org"
+
+      - name: generate files
+        run: |
+          cd ./.nswag-generator
+          dotnet run --genTsModel --updateVersion
+
+      - name: Install dependencies
+        working-directory: src/TypeScriptSDK
+        run: npm i
+
+      - name: Build module
+        working-directory: src/TypeScriptSDK
+        run: npm run build
+
+      - name: Publish to npm
+        working-directory: src/TypeScriptSDK
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+        run: npm publish --access public
+
+  UpdateDownstremRepo:
     name: Update dependencies
     if: github.ref == 'refs/heads/master'
     runs-on: ubuntu-latest
-    needs: build
+    needs: [buildCSharp, BuildTypeScript]
 
     steps:
-      - name: sleep for 10 minutes for PyPI update
-        run: sleep 600s
+      - name: Wait for NuGet package to be available
         shell: bash
+        run: |
+          PACKAGE_NAME="HoneybeeSchema"
+          PACKAGE_VERSION="${{ needs.build.outputs.tag }}"
+          MAX_ATTEMPTS=30
+          SLEEP_TIME=60
+
+          for ((i=1;i<=MAX_ATTEMPTS;i++)); do
+            echo "Checking for package $PACKAGE_NAME version $PACKAGE_VERSION (Attempt $i/$MAX_ATTEMPTS)..."
+            if dotnet nuget search $PACKAGE_NAME --source https://api.nuget.org/v3/index.json --prerelease --include-delisted | grep $PACKAGE_VERSION; then
+              echo "Package $PACKAGE_NAME version $PACKAGE_VERSION is available!"
+              exit 0
+            fi
+            echo "Package not available yet. Sleeping for $SLEEP_TIME seconds..."
+            sleep $SLEEP_TIME
+          done
+
+          echo "Package $PACKAGE_NAME version $PACKAGE_VERSION was not found after $MAX_ATTEMPTS attempts."
+          exit 1
 
       - name: Update dragonfly-schema-dotnet
         env:
